version: '3.8'

services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      
      - ./logs:/var/log/odoo
      - /path/to/enterprise:/mnt/enterprise-addons  # Añadir Enterprise
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    
 

    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo-web-data:
    name: odoo-18-docker_odoo-web-data
  odoo-db-data:
    name: odoo-18-docker_odoo-db-data